### ISSUE TITLE
Error when starting testing/development serve.

### ISSUE THREAD

**Issue by DiamondSwag** [SocketCluster/sc-phaser-sample#12]
1531271367807 - Worker 0 exited - Exit code: 1
1531271368185 - Origin: Worker (PID 9920)
   [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (C:\Users\Drew\Desktop\Django\Queen.io\node_modules\uws\uws.js:38:19)
    at Object.<anonymous> (C:\Users\Drew\Desktop\Django\Queen.io\node_modules\uws\uws.js:42:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at new SCServer (C:\Users\Drew\Desktop\Django\Queen.io\node_modules\socketcluster-server\scserver.js:97:18)
1531271368193 - Worker 0 exited - Exit code: 1
1531271368630 - Worker 0 exited - Exit code: 3221225786
1531271368646 - Origin: BrokerEngine (PID 4880)
   [Error] ProcessExitError: scBroker server at socket path \\.\pipe\socketcluster_e24aeafe-1ba5_02a88a8eb6_b0 exited
    at Server.<anonymous> (C:\Users\Drew\Desktop\Django\Queen.io\node_modules\sc-broker-cluster\index.js:371:19)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at Server.EventEmitter.emit (C:\Users\Drew\Desktop\Django\Queen.io\node_modules\sc-domain\index.js:12:31)
    at ChildProcess.<anonymous> (C:\Users\Drew\Desktop\Django\Queen.io\node_modules\sc-broker\index.js:82:10)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.EventEmitter.emit (C:\Users\Drew\Desktop\Django\Queen.io\node_modules\sc-domain\index.js:12:31)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by Slluxx** [comment]
+1

**Comment by rsimpsonn** [comment]
Me too

**Comment by stefanovolacom** [comment]
+1

**Comment by campbellgoe** [comment]
+1 on iMac - High Sierra - 10.13.6

**Comment by DrewRidley** [comment]
+1

**Comment by DrewRidley** [comment]
Very easy fix, simply just change the WebSocket engine to "ws".

**Comment by YNVoon** [comment]
> Very easy fix, simply just change the WebSocket engine to "ws".

Which WebSocket engine are you referring to?

**Comment by YNVoon** [comment]
Found that in server.js file. Just change the 'uws' to 'ws'.
