### ISSUE TITLE
Error: listen EADDRINUSE :::15454

### ISSUE THREAD

**Issue by noahcoetsee** [SocketCluster/sc-phaser-sample#4]
This is an error. Any idea what caused it when I ran the server.js using Cloud9.... I'm not sure what is going on!

`Error: listen EADDRINUSE :::15454
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Agent.Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Agent.Server.listen (net.js:1382:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:70:44)
    at node.js:974:3
`

**Comment by jondubois** [comment]
Sounds like you tried listening to a port which is already in use... Maybe it's used by a different instance of IOGrid. You can try running this in the console (warning, it will shut down all your Node.js processes):

```
killall node
```

Then try launching again.
